[[pages]]
path = "app"
name = "Start"
icon = "ğŸ "

[[pages]]
path = "pages/1_PV_mit_Speicher"
name = "PV mit Speicher"
icon = "ğŸ”‹"

[[pages]]
path = "pages/2_PV_ohne_Speicher"
name = "PV ohne Speicher"
icon = "â˜€ï¸"
